### ISSUE TITLE
Give a color to filters that cause entries not to show up.

### ISSUE THREAD

**Issue by gafderks** [gafderks/activiteitenbank#18]
Gives a good indication of the 'active' filters.

**Comment by gafderks** [comment]
This is hard to do because filtering is done per item. An item that does match the filter will remove the indication while the filter may still be active. It is hard to see that missing items were filtered by the current filter so we cannot be confident that we should keep the indication.

**Comment by mhverbakel** [comment]
From a user perspective, this is always hard to use. If you have a combination of two filters that never occurs, both filters would get a color? And then, if a filter value is added for a combination that occurs, then all color is dropped?

**Comment by gafderks** [comment]
@mhverbakel You can check-out the branch issue/18 and check out whether you find it hard to use.
